export const dataEleve = [
  {
    id: 1,
    username: "chillatt0",
    first_name: "Carole",
    email: "cfridaye0@netvibes.com",
    matricule: "36800-734",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 2,
    username: "uconnolly1",
    first_name: "Upton",
    email: "ukarus1@blogger.com",
    matricule: "0268-6316",
    role: 1,
    classes: [{ level: "Première", speciality: "C" }],
  },
  {
    id: 3,
    username: "gderuggiero2",
    first_name: "Gale",
    email: "gchessun2@hhs.gov",
    matricule: "51209-003",
    role: 1,
    classes: [{ level: "Sixième", speciality: "D" }],
  },
  {
    id: 4,
    username: "facomb3",
    first_name: "Fallon",
    email: "fduffil3@cbc.ca",
    matricule: "66993-935",
    role: 1,
    classes: [{ level: "Troisième", speciality: "A" }],
  },
  {
    id: 5,
    username: "wmongain4",
    first_name: "Wolfgang",
    email: "wpawson4@bigcartel.com",
    matricule: "51991-629",
    role: 1,
    classes: [{ level: "Terminale", speciality: "C" }],
  },
  {
    id: 6,
    username: "ncragg5",
    first_name: "Neill",
    email: "ndownham5@google.cn",
    matricule: "57955-5015",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 7,
    username: "fmquharge6",
    first_name: "Farah",
    email: "fhealeas6@columbia.edu",
    matricule: "0781-5238",
    role: 1,
    classes: [{ level: "Terminale", speciality: "D" }],
  },
  {
    id: 8,
    username: "rantony7",
    first_name: "Roselia",
    email: "rfilov7@auda.org.au",
    matricule: "48951-1135",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 9,
    username: "ccrum8",
    first_name: "Cyndie",
    email: "cgilligan8@ihg.com",
    matricule: "63629-3685",
    role: 1,
    classes: [{ level: "Terminale", speciality: "C" }],
  },
  {
    id: 10,
    username: "cdeighan9",
    first_name: "Corinna",
    email: "criddlesden9@independent.co.uk",
    matricule: "24385-961",
    role: 1,
    classes: [{ level: "Terminale", speciality: "C" }],
  },
  {
    id: 11,
    username: "bskoylesa",
    first_name: "Bobby",
    email: "bfencotta@house.gov",
    matricule: "68647-173",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 12,
    username: "eshakeladeb",
    first_name: "Enoch",
    email: "epresmanb@dailymotion.com",
    matricule: "51079-347",
    role: 1,
    classes: [{ level: "Terminale", speciality: "C" }],
  },
  {
    id: 13,
    username: "dmonroc",
    first_name: "Damara",
    email: "dbrouc@bloglines.com",
    matricule: "69017-201",
    role: 1,
    classes: [{ level: "Sixieme", speciality: "D" }],
  },
  {
    id: 14,
    username: "mfeathersd",
    first_name: "Mychal",
    email: "mtrillowd@smugmug.com",
    matricule: "41190-461",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 15,
    username: "bdreschere",
    first_name: "Brion",
    email: "bfilyashine@gnu.org",
    matricule: "65954-007",
    role: 1,
    classes: [{ level: "Seconde", speciality: "A" }],
  },
  {
    id: 16,
    username: "preimerf",
    first_name: "Patrizio",
    email: "phulettf@networksolutions.com",
    matricule: "43419-708",
    role: 1,
    classes: [{ level: "Troisieme", speciality: "A" }],
  },
  {
    id: 17,
    username: "rpercyg",
    first_name: "Rancell",
    email: "rspellsworthg@harvard.edu",
    matricule: "55154-6812",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 18,
    username: "cpursegloveh",
    first_name: "Clevie",
    email: "cgalbraethh@answers.com",
    matricule: "49288-0666",
    role: 1,
    classes: [{ level: "Sixieme", speciality: "A" }],
  },
  {
    id: 19,
    username: "jamoorei",
    first_name: "Jenelle",
    email: "jleftridgei@census.gov",
    matricule: "11994-090",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 20,
    username: "hdeleonj",
    first_name: "Hildegaard",
    email: "hstairsj@chicagotribune.com",
    matricule: "30142-913",
    role: 1,
    classes: [{ level: "Cinquime", speciality: "A" }],
  },
  {
    id: 21,
    username: "jbuzekk",
    first_name: "Jamill",
    email: "jfumagallik@oakley.com",
    matricule: "11822-9015",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 22,
    username: "rsaggsl",
    first_name: "Reinwald",
    email: "rgommeyl@foxnews.com",
    matricule: "55154-7566",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 23,
    username: "awhybrowm",
    first_name: "Ashli",
    email: "atunstallm@noaa.gov",
    matricule: "53489-150",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 24,
    username: "ktarzeyn",
    first_name: "Keri",
    email: "krivaln@dell.com",
    matricule: "62003-001",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
  {
    id: 25,
    username: "dsuermeiero",
    first_name: "Delcine",
    email: "derrolo@foxnews.com",
    matricule: "0054-0545",
    role: 1,
    classes: [{ level: "Terminale", speciality: "A" }],
  },
];
